### PR TITLE
New release supporting 2018 edition, new names, etc.

### PR DESCRIPTION
**Pull request by jamesmunns**
This is my current WIP. This is not ready to merge.

All PRs in this family:

* [nrf52832-pac]
* [nrf52840-pac]
* [nrf52-hal]

[nrf52832-pac]: https://github.com/nrf-rs/nrf52832-pac/pull/11
[nrf52840-pac]: https://github.com/nrf-rs/nrf52840-pac/pull/2
[nrf52-hal]: https://github.com/nrf-rs/nrf52-hal/pull/32

### CODE REVIEW

**Comment by jamesmunns** [comment]
Note: I have used master of svd2rust to regenerate this code. As v0.14 is dropping soon, I expect to use that if it is ready in time.

I also needed to modify the SVD to not use hex numbers in the `<dim>` fields. This made svd2rust unhappy,

**Comment by jamesmunns** [comment]
Hey @nrf-rs/nrf52, I believe this is ready to land now. I have already cut a release and published on crates.io as `0.6.0-beta.1`. Could you please test with your crates locally, and let me know how it goes?

I'd like to merge this sooner than later, and if we need to iterate on `master` before we cut the final `0.6.0` release, that works for me.

Please see the related issues linked above for this family of PRs.

**Review by hannobraun — COMMENTED** [review]
(Note: Copy-pasted my comment from https://github.com/nrf-rs/nrf52832-pac/pull/11, as the same applies here.)

I don't have time right now to review the changes from the svd2rust update, but the rest looks good to me.

I'm concerned though about moving from @wez's svd2rust fork back to mainline (see https://github.com/nrf-rs/nrf52832-pac/issues/3). You addressed part of the problem in the SVD file itself, but what about the handling of `derivedFrom`? Is that relevant in this crate?

**Comment by jamesmunns** [comment]
See comments from https://github.com/nrf-rs/nrf52832-pac/pull/11#issuecomment-439689413 - I believe these are ready to ship as-is.

**Comment by jamesmunns** [comment]
@hannobraun @wez, final call here too! will plan on merging in appx 24 hours.

**Comment by jamesmunns** [comment]
Okay, I lied, I am going to run with it. We can drop a point release if there are any issues, I have some time tonight and would like this to be done done. Sorry for the noise.

**Comment by hannobraun** [comment]
Looks good to me!

**Pull request merged**
